CREATE DATABASE FILMESDOCINEMA;

CREATE TABLE `PRODUTORAS` (
`ID_COMPANHIA` INT(11) NOT NULL,
`NOME_PRODUTORA` VARCHAR(30) NOT NULL
);

CREATE TABLE `FILMES` (
`ID_FILME` INT(11) NOT NULL,
`TITULO_FILME` VARCHAR(60) NOT NULL,
`CLASSIFICACAO_IMDB` FLOAT(10) NOT NULL,
`ANO_LANCAMENTO` YEAR(4) NOT NULL,
`CUSTO` FLOAT(30) NOT NULL,
`FATURAMENTO` FLOAT(30) NOT NULL,
`ID_COMPANHIA_ID_COMPANHIA` INT(11) NOT NULL,
`IDIOMA` VARCHAR(10) NOT NULL
);

INSERT INTO `PRODUTORAS` VALUES (1, 'COLUMBIA PICTURES'), (2, 'PARAMOUNT PICTURES'),
(3, 'WARNER BROS. PICTURES'), (4, 'UNITED ARTISTS'), (5, 'UNIVERSAL PICTURES'),
(6, 'NEW LINE CINEMA'), (7, 'MIRAMAX FILMS'), (8, 'PRODUZIONI EUROPEE ASSOCIATE'),
(9, 'BUENA VISTA'), (10, 'STUDIOCANAL');

INSERT INTO `FILMES` VALUES (1, 'DE VOLTA PARA O FUTURO', '9.2', 1994, 25.00, 73.30, 1, 'INGLÊS'),
(2, 'O PODEROSO CHEFÃO', 9.2, 1972, 7.20, 291.00, 2, 'ITALIANO'),
(3, 'CAVALEIRO NEGRO', 9.0, 2008, 185.00, 1006.00, 3, 'INGLÊS'),
(4, 'O PODEROSO CHEFÃO - PARTE II', 8.9, 1974, 13.00, 93.00, 2, 'ITALIANO'),
(5, 'O NOME DO TERRORISTA', 9.0, 1993, 3.40, 2.00, 4, 'ITALIANO'),
(6, 'A LISTA DE SCHINDLER', 8.9, 1993, 22.00, 322.20, 5, 'HEBRAICO'),
(7, 'O SENHOR DOS ANÉIS - O RETORNO DO REI', 8.9, 2003, 94.00, 1146.00, 6, 'INGLÊS'),
(8, 'PULP FICTION', 8.8, 1994, 8.50, 213.90, 7, 'INGLÊS'),
(9, 'O SENHOR DOS ANÉIS - A SOCIEDADE DO ANEL', 8.8, 2001, 93.00, 898.20, 1, 'INGLÊS'),
(10, 'OS TRÊS PATETAS', 8.8, 1966, 1.20, 38.90, 8, 'ESPANHOL');

SELECT PRODUTORAS.NOME_PRODUTORA, FILMES.TITULO_FILME, FILMES.FATURAMENTO, FILMES.IDIOMA
FROM PRODUTORAS, FILMES;

SELECT FILMES.TITULO_FILME, FILMES.IDIOMA
FROM FILMES
WHERE FILMES.IDIOMA != 'INGLÊS';

SELECT FILMES.TITULO_FILME, FILMES.CUSTO, FILMES.FATURAMENTO, FILMES.ANO_LANCAMENTO
FROM FILMES
WHERE FILMES.FATURAMENTO > FILMES.CUSTO AND FILMES.ANO_LANCAMENTO BETWEEN 1990 AND 2000;

SELECT PRODUTORAS.ID_COMPANHIA
FROM PRODUTORAS
WHERE  PRODUTORAS.ID_COMPANHIA NOT IN (
SELECT ID_COMPANHIA_ID_COMPANHIA
FROM FILMES
WHERE ID_COMPANHIA_ID_COMPANHIA IS NOT NULL
);

SELECT FILMES.TITULO_FILME, FILMES.FATURAMENTO, FILMES.CLASSIFICACAO_IMDB
FROM FILMES
WHERE FILMES.TITULO_FILME LIKE '%PODEROSO%';

SELECT PRODUTORAS.NOME_PRODUTORA, FILMES.CLASSIFICACAO_IMDB, FILMES.IDIOMA
FROM PRODUTORAS, FILMES
WHERE FILMES.IDIOMA = 'ITALIANO' AND  FILMES.CLASSIFICACAO_IMDB > 9;

SELECT FILMES.TITULO_FILME, FILMES.CUSTO, FILMES.IDIOMA
FROM FILMES
WHERE FILMES.CUSTO < 13.00 AND FILMES.IDIOMA != 'ITALIANO';
